FROM golang:1.26-trixie

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM gcr.io/distroless/static-debian13

COPY --from=builder /app/server /server

CMD ["/server"]

