FROM golang:1.26-trixie

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM scratch

COPY --from=builder /app/server /server

CMD ["/server"]

